export const CANDIDATE_LIST_REQUEST = 'CANDIDATE_LIST_REQUEST';
export const CANDIDATE_LIST_SUCCESS = 'CANDIDATE_LIST_SUCCESS';
export const CANDIDATE_LIST_FAIL = 'CANDIDATE_LIST_FAIL';
export const CANDIDATE_LIST_RESET = 'CANDIDATE_LIST_RESET';

export const CANDIDATE_CREATE_REQUEST = 'CANDIDATE_CREATE_REQUEST';
export const CANDIDATE_CREATE_SUCCESS = 'CANDIDATE_CREATE_SUCCESS';
export const CANDIDATE_CREATE_FAIL = 'CANDIDATE_CREATE_FAIL';
export const CANDIDATE_CREATE_RESET = 'CANDIDATE_CREATE_RESET';

export const CANDIDATE_UPDATE_REQUEST = 'CANDIDATE_UPDATE_REQUEST';
export const CANDIDATE_UPDATE_SUCCESS = 'CANDIDATE_UPDATE_SUCCESS';
export const CANDIDATE_UPDATE_FAIL = 'CANDIDATE_UPDATE_FAIL';
export const CANDIDATE_UPDATE_RESET = 'CANDIDATE_UPDATE_RESET';
