export const VOTE_CREATE_REQUEST = 'VOTE_REQUEST';
export const VOTE_CREATE_SUCCESS = 'VOTE_CREATE_SUCCESS';
export const VOTE_CREATE_FAIL = 'VOTE_CREATE_FAIL';
export const VOTE_CREATE_RESET = 'VOTE_CREATE_RESET';